CREATE TYPE transaction_status AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED',
    'CANCELLED'
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    total_amount NUMERIC(19, 2) NOT NULL CHECK (total_amount >= 0),
    status transaction_status NOT NULL DEFAULT 'PENDING',
    external_reference VARCHAR(255) NOT NULL,
    mp_payment_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_transaction_external_reference
    ON transaction (external_reference);

CREATE INDEX idx_transaction_email
    ON transaction (email);

CREATE INDEX idx_transaction_status
    ON transaction (status);

CREATE FUNCTION set_transaction_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_transaction_updated_at
    BEFORE UPDATE ON transaction
    FOR EACH ROW
    EXECUTE FUNCTION set_transaction_updated_at();

CREATE TABLE lucky_number (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number TEXT NOT NULL,
    email VARCHAR(320) NOT NULL,
    transaction_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_lucky_number_number UNIQUE (number),
    CONSTRAINT fk_lucky_number_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transaction (id)
);

CREATE INDEX idx_lucky_number_email
    ON lucky_number (email);

CREATE INDEX idx_lucky_number_transaction_id
    ON lucky_number (transaction_id);

CREATE TABLE raffle_draw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    winning_number TEXT NOT NULL,
    winner_email VARCHAR(320) NOT NULL,
    drawn_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    CONSTRAINT uq_admin_user_username UNIQUE (username),
    CONSTRAINT chk_admin_user_password_hash_length
        CHECK (char_length(password_hash) = 60)
);
