ALTER TABLE raffle_config
    ADD COLUMN groom_name VARCHAR(120) NOT NULL DEFAULT 'Jose Carlos',
    ADD COLUMN bride_name VARCHAR(120) NOT NULL DEFAULT 'Paula',
    ADD COLUMN color_ivory VARCHAR(7) NOT NULL DEFAULT '#F7F1E6',
    ADD COLUMN color_ivory_deep VARCHAR(7) NOT NULL DEFAULT '#F0E8D8',
    ADD COLUMN color_ink VARCHAR(7) NOT NULL DEFAULT '#2B2419',
    ADD COLUMN color_ink_soft VARCHAR(7) NOT NULL DEFAULT '#5B5140',
    ADD COLUMN color_green VARCHAR(7) NOT NULL DEFAULT '#24402E',
    ADD COLUMN color_green_deep VARCHAR(7) NOT NULL DEFAULT '#152A1D',
    ADD COLUMN color_wine VARCHAR(7) NOT NULL DEFAULT '#7A2E33',
    ADD COLUMN color_gold VARCHAR(7) NOT NULL DEFAULT '#B8935A',
    ADD COLUMN color_gold_soft VARCHAR(7) NOT NULL DEFAULT '#DCC79A',
    ADD COLUMN color_line VARCHAR(7) NOT NULL DEFAULT '#D9CBAA';
