ALTER TYPE transaction_status ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE transaction_status ADD VALUE IF NOT EXISTS 'CHARGED_BACK';
ALTER TYPE transaction_status ADD VALUE IF NOT EXISTS 'IN_MEDIATION';
